---
- name: Bring down loadbalancer
  hosts: loadbalancer
  become: true
  tasks:
    - name: Stop nginx
      service:
        name: nginx
        state: stopped

    - name: Verfiy port 80 is drained
      wait_for:
        port: 80
        state: drained

- name: Bring down web server
  hosts: webserver
  become: true
  tasks:
    - name: Stop apache2
      service:
        name: apache2
        state: stopped

    - name: Verfiy port 80 is stopped
      wait_for:
        port: 80
        state: stopped

- name: Restart database
  hosts: database
  become: true
  tasks:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted

    - name: Verfiy port 3306 is mysql
      wait_for:
        host: "{{ ansible_eth1.ipv4.address }}"
        port: 3306
        state: started


- name: Bring up web server
  hosts: webserver
  become: true
  tasks:
    - name: Start apache2
      service: 
        name: apache2
        state: started

    - name: Verfiy port 80 apache2
      wait_for:
        port: 80
        state: started

- name: Bring up loadbalancer
  hosts: loadbalancer
  become: true
  tasks:
    - name: Start loadbalancer
      service:
        name: nginx
        state: started 
       
    - name: Verfiy port 80 is loadbalancer
      wait_for:
        port: 80
        state: started

